workspace = { members = ["examples/stm32-nucleo-f411re"] }
[package]
name = "tsl2591-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
